=== Alhadis/Record-Collection/DTDs/inventory.dtd
<!--
	TODO: Learn more about XML catalogues.
	* https://en.wikipedia.org/wiki/XML_catalog
	* https://www.oasis-open.org/committees/entity/spec.html
-->

<!ELEMENT inventory (title|modified|currency|artists|items)*>
<!ATTLIST inventory
	xmlns       CDATA #FIXED "http://alhad.is/xml/record-collection.dtd"
	xmlns:xlink CDATA #FIXED "http://www.w3.org/1999/xlink"
	xml:lang    CDATA #IMPLIED>

<!ELEMENT title (#PCDATA)>
<!ATTLIST title
	xml:lang CDATA #IMPLIED>

<!ELEMENT modified (#PCDATA)>
<!ELEMENT currency (#PCDATA)>


<!--
	List of recording artists who produced listed recordings.
	
	Helpful URL conversions:
		^https?://www\.discogs\.com/artist/(\d+)(?:-[^/]*)?$
		<discogs>$1</discogs>

		^https?://www\.metal-archives\.com/bands/[^/]*/(\d+)$
		^https?://www\.metal-archives\.com/band/view/id/(\d+)$
		<ma>$1</ma>

		^https?://rateyourmusic\.com/artist/([^\s/]+)
		<rym>$1</rym>

		^https?://([^\s.@:]+)\.bandcamp\.com/?$
		<bc>$1</bc>
-->
<!ELEMENT artists (artist)*>
<!ELEMENT artist (name|country|refs)*>
<!ATTLIST artist
	ref        IDREF #IMPLIED
	xml:id     ID    #IMPLIED
	xlink:href CDATA #IMPLIED>


<!-- List of entity names -->
<!ELEMENT names (name)*>
<!ATTLIST names
	format    CDATA #IMPLIED
	separator CDATA " / ">
<!ELEMENT name (#PCDATA|abbr)*>
<!ATTLIST name xml:lang CDATA #IMPLIED>


<!ELEMENT abbr (#PCDATA)>
<!ATTLIST abbr
	text     CDATA #REQUIRED
	type     (acronym|initialism|contraction|crasis|gramogram|numeronym|symbol) #IMPLIED
	show     (auto|true|false) "auto"
	xml:lang CDATA #IMPLIED>

<!ELEMENT country (#PCDATA)>
<!ATTLIST country region CDATA #IMPLIED>

<!ELEMENT refs (bc|discogs|fb|ma|mbid|rym|wd)*>

<!--
	Bandcamp user ID; specifies subdomain of artist page, optionally with a link
	to a specific track or release published by said artist.
	<bc>slayer</bc>                           ⇒  https://slayer.bandcamp.com/
	<bc album="hell-awaits">slayer</bc>       ⇒  https://slayer.bandcamp.com/album/hell-awaits
	<bc track="the-antichrist-2">slayer</bc>  ⇒  https://slayer.bandcamp.com/track/the-antichrist-2
-->
<!ELEMENT bc (#PCDATA)>
<!ATTLIST bc
	album CDATA #IMPLIED
	track CDATA #IMPLIED>

<!--
	Discogs ID. Format is an unsigned integer with a possible trailing slug separated by a dash.
	<discogs>45467</discogs>             ⇒  https://www.discogs.com/artist/45467
	<discogs>45467-Pink-Floyd</discogs>  ⇒  https://www.discogs.com/artist/45467-Pink-Floyd
-->
<!ELEMENT discogs (#PCDATA)>
<!ATTLIST discogs type (auto|artist|label|master|release) "auto">

<!--
	Facebook ID or username. Pages must be publicly-readable; purely-numeric IDs are
	preferred over user-defined handles, which are prone to change over time.
-->
<!ELEMENT fb (#PCDATA)>

<!--
	Metal Archives ID. Format is an unsigned integer corresponding to a typed-entity's database ID.
	<ma>17</ma>                 ⇒ https://www.metal-archives.com/band/view/id/17
	<ma type="artist">22</ma>   ⇒ https://www.metal-archives.com/artist/view/id/22
	<ma type="release">199</ma> ⇒ https://www.metal-archives.com/release/view/id/199
-->
<!ELEMENT ma (#PCDATA)>
<!ATTLIST ma type (auto|band|artist|release|label) "auto">

<!-- Self-explanatory reference types -->
<!ELEMENT mbid (#PCDATA)>  <!-- MusicBrainz Identifier -->
<!ELEMENT rym  (#PCDATA)>  <!-- Rate Your Music artist or release page -->
<!ELEMENT wd   (#PCDATA)>  <!-- Wikidata item -->






<!ELEMENT items   (release, note?, price?)>
<!ELEMENT release ((artist|artists), copies?, format, (name|names), note?, refs?, version*)>
<!ELEMENT copies  (#PCDATA)>
<!ELEMENT format  (#PCDATA)>
<!ELEMENT note    (#PCDATA)>
<!ELEMENT version (name|format|refs|price)*>
<!ATTLIST version main (true) #FIXED "true">

=== Alhadis/Record-Collection/record-collection.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE inventory SYSTEM "DTDs/inventory.dtd">
<inventory xml:lang="en">
	<title>Alhadis’s record collection</title>
	<modified>2025-06-23T07:49:59+10:00</modified>
	<currency>AUD</currency>

	<artists>
		<artist xml:id="16-bitch-pile-up">
			<name>16 Bitch Pile-up</name>
			<country region="Columbus, Ohio">US</country>
			<refs>
				<discogs>346626</discogs>
				<mbid>90479cfd-d1bf-45b1-a53d-753815fbeb8d</mbid>
				<rym>16-bitch-pile-up</rym>
			</refs>
		</artist>
		
		<artist xml:id="3xa">
			<name><abbr text="Abdominal Aortic Aneurysm" show="true">3XA</abbr></name>
			<country>US</country>
			<refs>
				<discogs>3822217</discogs>
				<mbid>4e23120c-4e2b-4038-a627-77a0ba116d9d</mbid>
				<rym>3xa</rym>
			</refs>
		</artist>
		
		<artist xml:id="abjection-ritual">
			<name>Abjection Ritual</name>
			<country>US</country>
			<refs>
				<bc>abjectionritual</bc>
				<discogs>4249242</discogs>
				<mbid>81f610ee-5afa-450a-a38e-3f7b8bf70a98</mbid>
				<rym>abjection-ritual</rym>
			</refs>
		</artist>
		
		<artist xml:id="actuary">
			<name>Actuary</name>
			<country>US</country>
			<refs>
				<discogs>1153853</discogs>
				<mbid>8ad1b198-d7ef-44b0-82cb-7b4fe795a952</mbid>
				<rym>actuary</rym>
				<wd>Q60308196</wd>
			</refs>
		</artist>
		
		<artist xml:id="aderlating">
			<name xml:lang="nl">Aderlating</name>
			<country>NL</country>
			<refs>
				<bc>gnawtheirtongues</bc>
				<discogs>1365216</discogs>
				<fb>137622832995217</fb>
				<mbid>0cb960f9-091e-44b6-b215-8d035873edc7</mbid>
			</refs>
		</artist>
		
		<artist xml:id="aeon-nought">
			<name>Æon Nought</name>
			<country>NL</country>
			<refs>
				<discogs>3937004</discogs>
				<mbid>9cccf6c7-bcb2-48b7-b05f-7bcd5fd6d468</mbid>
				<rym>aeon_nought</rym>
			</refs>
		</artist>
		
		<artist xml:id="aevangelist">
			<name>Ævangelist</name>
			<country>US</country>
			<refs>
				<bc>aevangelist</bc>
				<discogs>3164829</discogs>
				<fb>100063482675488</fb>
				<ma>3540323826</ma>
				<mbid>06f5494d-b22a-457e-8aef-328d2c83a5fc</mbid>
				<wd>Q17710070</wd>
			</refs>
		</artist>
		
		<artist xml:id="afonia">
			<name>Afonia</name>
			<country>RU</country>
			<refs>
				<bc>afoniaural</bc>
				<discogs>2489434</discogs>
			</refs>
		</artist>
		
		<artist xml:id="agathocles">
			<name>Agathocles</name>
			<country>BE</country>
			<refs>
				<bc>capitalscumagathocles</bc>
				<discogs>252868</discogs>
				<fb>100063591579662</fb>
				<ma>2649</ma>
				<mbid>4a2e0104-e6ea-42ec-9399-1f670418c134</mbid>
				<wd>Q391393</wd>
			</refs>
		</artist>
		
		<artist xml:id="akhlys">
			<name>Akhlys</name>
			<country>US</country>
			<refs>
				<bc>akhlys</bc>
				<discogs>1642547</discogs>
				<fb>100045704862350</fb>
				<ma>3540395486</ma>
				<mbid>fae0a90c-22ac-4065-a904-514cfca30ad9</mbid>
			</refs>
		</artist>
		
		<artist xml:id="alien-possession">
			<name>Alien Possession</name>
			<country>NL</country>
			<refs>
				<discogs>3716708</discogs>
				<ma>3540375700</ma>
				<mbid>86bf510c-6fbb-4afc-884a-c4f2d61da0f5</mbid>
			</refs>
		</artist>
		
		<artist xml:id="altar-of-plagues">
			<name>Altar of Plagues</name>
			<country region="Cork">IE</country>
			<refs>
				<bc>altarofplagues</bc>
				<discogs>1484207</discogs>
				<fb>100045255787331</fb>
				<ma>85064</ma>
				<mbid>33fd78d9-3b93-49a2-9ccf-0d90b527fc8d</mbid>
				<rym>altar_of_plagues</rym>
				<wd>Q4736180</wd>
			</refs>
		</artist>
		
		<artist xml:id="amnis-nihili">
			<name>Amnis Nihili</name>
			<country region="Athens">GR</country>
			<refs>
				<bc>amnisnihili</bc>
				<discogs>2438470</discogs>
				<ma>3540327677</ma>
				<mbid>8200ce21-e3a9-4e41-b342-000124ff0378</mbid>
			</refs>
		</artist>
		
		<artist xml:id="ana-venus">
			<name>Ana Venus</name>
			<country>HU</country>
			<refs>
				<bc>anavenus</bc>
				<discogs>2864748</discogs>
				<mbid>feced732-9436-49af-98e8-4d2fd616c1de</mbid>
			</refs>
		</artist>
		
		<artist xml:id="anaal-nathrakh">
			<name>Anaal Nathrakh</name>
			<country region="Birmingham">GB</country>
			<refs>
				<bc>anaalnathrakh</bc>
				<discogs>252834</discogs>
				<fb>100050676510566</fb>
				<ma>1314</ma>
				<mbid>9bf82496-9d7b-43ac-b3ee-076c90ada9d7</mbid>
				<rym>anaal-nathrakh</rym>
				<wd>Q483140</wd>
			</refs>
		</artist>
		
		<artist xml:id="ancient-niggurath">
			<name>Ancient Niggurath</name>
			<country region="Trois-Rivières, Quebec">CA</country>
			<refs>
				<discogs>5109923</discogs>
				<ma>3540352253</ma>
			</refs>
		</artist>
		
		<artist xml:id="anenzephalia">
			<name>Anenzephalia</name>
			<country>DE</country>
			<refs>
				<discogs>51878</discogs>
				<mbid>926872f9-3d2c-49ef-8b70-402a116c7ee0</mbid>
				<rym>anenzephalia</rym>
				<wd>Q4761684</wd>
			</refs>
		</artist>
		
		<artist xml:id="antaeus">
			<name>Antaeus</name>
			<country region="Maisons-Laffitte, Île-de-France">FR</country>
			<refs>
				<bc>antaeusofficial</bc>
				<discogs>259922</discogs>
				<fb>100050691240175</fb>
				<ma>2170</ma>
				<mbid>86e4ecee-d1a3-4d95-91d5-e097aaf18620</mbid>
				<wd>Q570552</wd>
			</refs>
		</artist>
		
		<artist xml:id="arcanum-inferi">
			<name>Arcanum Inferi</name>
			<country region="Misterbianco, Catania, Sicily">IT</country>
			<refs>
				<discogs>2873360</discogs>
				<fb>100063921181194</fb>
				<ma>3540304805</ma>
			</refs>
		</artist>
		
		<artist xml:id="atrax-morgue">
			<name>Atrax Morgue</name>
			<country>IT</country>
			<refs>
				<discogs>73014</discogs>
				<mbid>395c43f0-2427-4248-99f5-dee095b845a6</mbid>
				<rym>atrax_morgue</rym>
				<wd>Q3846033</wd>
			</refs>
		</artist>
		
		<artist xml:id="bastardass">
			<name>Bastardass</name>
			<country>US</country>
			<refs>
				<discogs>1436318</discogs>
				<mbid>dc60acce-8a20-466c-8be9-df2a669344e4</mbid>
				<rym>bastardass</rym>
			</refs>
		</artist>
		
		<artist xml:id="belphegor">
			<name>Belphegor</name>
			<country region="Salzburg">AT</country>
			<refs>
				<bc>belphegor-austria</bc>
				<discogs>282546</discogs>
				<fb>100044322613473</fb>
				<ma>1952</ma>
				<mbid>a41cc6b0-ff0c-4331-9add-907025607e95</mbid>
				<rym>belphegor</rym>
				<wd>Q589580</wd>
			</refs>
		</artist>
		
		<artist xml:id="black-cop">
			<name>Black Cop</name>
			<country region="Glasgow, Scotland">GB</country>
			<refs>
				<bc>black-cop</bc>
				<discogs>4033553</discogs>
			</refs>
		</artist>
		
		<artist xml:id="blackhumour">
			<name>Blackhumour</name>
			<country region="Vancouver, British Columbia">CA</country>
			<refs>
				<discogs>80079</discogs>
				<mbid>9cd2699b-2c77-4c83-83f1-0d980ebdfeea</mbid>
				<rym>blackhumour</rym>
			</refs>
		</artist>
		
		<artist xml:id="blut-aus-nord">
			<name xml:lang="de">Blut aus Nord</name>
			<country region="Mondeville, Normandy">FR</country>
			<refs>
				<bc>blutausnord</bc>
				<discogs>265571</discogs>
				<fb>100044399050434</fb>
				<ma>2371</ma>
				<mbid>c21db200-1f7c-4c23-b518-cf7fac6b8e85</mbid>
				<rym>blut-aus-nord</rym>
				<wd>Q632229</wd>
			</refs>
		</artist>
		
		<artist xml:id="bob-bellerue">
			<name>Bob Bellerue</name>
			<country>US</country>
			<refs>
				<bc>bobbellerue</bc>
				<discogs>378554</discogs>
				<mbid>24efabe6-06b0-4302-b73b-891322928629</mbid>
				<rym>bob_bellerue</rym>
				<wd>Q4931789</wd>
			</refs>
		</artist>
		
		<artist xml:id="boneache">
			<name>Bone Ache</name>
			<country>BR</country>
			<refs>
				<discogs>2733001</discogs>
				<fb>100068215292186</fb>
				<mbid>6ebef50d-c87b-4cd7-b849-c0ab1346927d</mbid>
			</refs>
		</artist>
		
		<artist xml:id="bowel-rot">
			<name>Bowel Rot</name>
			<country>US</country>
			<refs>
				<discogs>2802424</discogs>
			</refs>
		</artist>
		
		<artist xml:id="bradymenorrhoea">
			<name>Bradymenorrhoea</name>
			<country>US</country>
			<refs>
				<discogs>2476691</discogs>
			</refs>
		</artist>
		
		<artist xml:id="branched-vein-sarcoma">
			<name>Branched Vein Sarcoma</name>
			<country>US</country>
			<refs>
				<discogs>4446449</discogs>
			</refs>
		</artist>
		
		<artist xml:id="brighter-death-now">
			<name>Brighter Death Now</name>
			<country>SE</country>
			<refs>
				<bc>brighterdeathnow</bc>
				<discogs>24658</discogs>
				<mbid>60bf0dce-6daa-4ef0-b9b7-0100a185f42a</mbid>
				<rym>brighter_death_now</rym>
				<wd>Q9179347</wd>
			</refs>
		</artist>
		
		<artist xml:id="coupo">
			<name><abbr type="initialism" text="Carcinomas of Unknown Primary Origin">C.O.U.P.O.</abbr></name>
			<country>US</country>
			<refs>
				<discogs>4083448</discogs>
			</refs>
		</artist>
		
		<artist xml:id="caffa">
			<name>Caffa</name>
			<country region="Oakland, California">US</country>
			<refs>
				<bc>caffa</bc>
				<discogs>3398808</discogs>
				<fb>100063719374158</fb>
				<ma>3540368026</ma>
				<mbid>8f8bc2ae-2430-430a-8e46-996f0877461c</mbid>
			</refs>
		</artist>
		
		<artist xml:id="caligula031">
			<name>Caligula031</name>
			<country>IT</country>
			<refs>
				<bc>caligula031</bc>
				<discogs>1830045</discogs>
				<mbid>7ec96cdb-1dea-42c5-b0be-a8f98ddc767e</mbid>
				<rym>caligula031</rym>
			</refs>
		</artist>
		
		<artist xml:id="cancer-makhluk">
			<name>Cancer Makhluk</name>
			<country>AU</country>
			<refs>
				<discogs type="label">1026725</discogs>
				<ma type="artist">209273</ma>
			</refs>
		</artist>
		
		<artist xml:id="carlos-villena">
			<name>Carlos Villena</name>
			<country>ES</country>
			<refs>
				<discogs>1087230</discogs>
				<mbid>9c232e38-957c-4432-ae27-5f7f92fe2aae</mbid>
				<rym>carlos_villena</rym>
			</refs>
		</artist>
		
		<artist xml:id="carpathian-forest">
			<name>Carpathian Forest</name>
			<country>NO</country>
			<refs>
				<bc>carpathianforest</bc>
				<discogs>259817</discogs>
				<fb>100044324864926</fb>
				<ma>147</ma>
				<mbid>69fa5c49-12ec-4c86-a238-4e07cc6d1a7d</mbid>
				<rym>carpathian-forest</rym>
				<wd>Q160111</wd>
			</refs>
		</artist>
		
		<artist xml:id="catacombs-of-doom">
			<name>Catacombs of Doom</name>
